sudo: required
language: go
go_import_path: github.com/ethereum/go-ethereum
services: skip
before_install: skip

jobs:
  include:
  - stage: Build and test
    os: linux
    dist: trusty
    go: 1.9.x
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - go run build/ci.go test -coverage
  - os: linux
    dist: trusty
    go: '1.10'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - go run build/ci.go test -coverage
  - os: osx
    sudo: false
    go: '1.10'
    script:
    - unset -f cd
    - brew update
    - brew cask install osxfuse
    - go run build/ci.go install
    - go run build/ci.go test -coverage
  - stage: Lint
    os: linux
    sudo: false
    dist: trusty
    go: '1.10'
    env:
    - lint
    git:
      submodules: false
    script:
    - go run build/ci.go lint
  - stage: Build and push Docker image
    services:
      - docker
    before_install:
      - docker build -t tomochain/tomochain .
      - docker run tomochain/tomochain
    deploy:
      provider: script
      script: bash docker_push.sh
      on:
        branch: travis
  - stage: Trigger rebuild of infrastructure image
    sudo: false
script: bash docker_rebuild.sh
